
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace EnttSharp.Entities
{

    public interface IEntityView<T1>  : IEntityView
    {
        void Apply(ViewDelegates.Apply<T1> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TContext, T1> bulk);

    }

    public interface IPersistentEntityView<T1>  : IEntityView<T1>
    {
        int Count { get; }
    }

    public interface IEntityView<T1, T2>  : IEntityView
    {
        void Apply(ViewDelegates.Apply<T1, T2> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TContext, T1, T2> bulk);

    }

    public interface IPersistentEntityView<T1, T2>  : IEntityView<T1, T2>
    {
        int Count { get; }
    }

    public interface IEntityView<T1, T2, T3>  : IEntityView
    {
        void Apply(ViewDelegates.Apply<T1, T2, T3> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TContext, T1, T2, T3> bulk);

    }

    public interface IPersistentEntityView<T1, T2, T3>  : IEntityView<T1, T2, T3>
    {
        int Count { get; }
    }

    public interface IEntityView<T1, T2, T3, T4>  : IEntityView
    {
        void Apply(ViewDelegates.Apply<T1, T2, T3, T4> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TContext, T1, T2, T3, T4> bulk);

    }

    public interface IPersistentEntityView<T1, T2, T3, T4>  : IEntityView<T1, T2, T3, T4>
    {
        int Count { get; }
    }

    public interface IEntityView<T1, T2, T3, T4, T5>  : IEntityView
    {
        void Apply(ViewDelegates.Apply<T1, T2, T3, T4, T5> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TContext, T1, T2, T3, T4, T5> bulk);

    }

    public interface IPersistentEntityView<T1, T2, T3, T4, T5>  : IEntityView<T1, T2, T3, T4, T5>
    {
        int Count { get; }
    }

    public interface IEntityView<T1, T2, T3, T4, T5, T6>  : IEntityView
    {
        void Apply(ViewDelegates.Apply<T1, T2, T3, T4, T5, T6> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TContext, T1, T2, T3, T4, T5, T6> bulk);

    }

    public interface IPersistentEntityView<T1, T2, T3, T4, T5, T6>  : IEntityView<T1, T2, T3, T4, T5, T6>
    {
        int Count { get; }
    }

    public interface IEntityView<T1, T2, T3, T4, T5, T6, T7>  : IEntityView
    {
        void Apply(ViewDelegates.Apply<T1, T2, T3, T4, T5, T6, T7> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TContext, T1, T2, T3, T4, T5, T6, T7> bulk);

    }

    public interface IPersistentEntityView<T1, T2, T3, T4, T5, T6, T7>  : IEntityView<T1, T2, T3, T4, T5, T6, T7>
    {
        int Count { get; }
    }

  

}
