
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace EnTTSharp.Entities
{

    public interface IEntityView<TEntityKey, T1>  : IEntityView<TEntityKey>
        where TEntityKey: IEntityKey
    {
        void Apply(ViewDelegates.Apply<TEntityKey, T1> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TEntityKey, TContext, T1> bulk);

    }

    public interface IPersistentEntityView<TEntityKey, T1>  : IEntityView<TEntityKey, T1>
        where TEntityKey: IEntityKey
    {
        int Count { get; }
    }

    public interface IEntityView<TEntityKey, T1, T2>  : IEntityView<TEntityKey>
        where TEntityKey: IEntityKey
    {
        void Apply(ViewDelegates.Apply<TEntityKey, T1, T2> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TEntityKey, TContext, T1, T2> bulk);

    }

    public interface IPersistentEntityView<TEntityKey, T1, T2>  : IEntityView<TEntityKey, T1, T2>
        where TEntityKey: IEntityKey
    {
        int Count { get; }
    }

    public interface IEntityView<TEntityKey, T1, T2, T3>  : IEntityView<TEntityKey>
        where TEntityKey: IEntityKey
    {
        void Apply(ViewDelegates.Apply<TEntityKey, T1, T2, T3> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TEntityKey, TContext, T1, T2, T3> bulk);

    }

    public interface IPersistentEntityView<TEntityKey, T1, T2, T3>  : IEntityView<TEntityKey, T1, T2, T3>
        where TEntityKey: IEntityKey
    {
        int Count { get; }
    }

    public interface IEntityView<TEntityKey, T1, T2, T3, T4>  : IEntityView<TEntityKey>
        where TEntityKey: IEntityKey
    {
        void Apply(ViewDelegates.Apply<TEntityKey, T1, T2, T3, T4> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TEntityKey, TContext, T1, T2, T3, T4> bulk);

    }

    public interface IPersistentEntityView<TEntityKey, T1, T2, T3, T4>  : IEntityView<TEntityKey, T1, T2, T3, T4>
        where TEntityKey: IEntityKey
    {
        int Count { get; }
    }

    public interface IEntityView<TEntityKey, T1, T2, T3, T4, T5>  : IEntityView<TEntityKey>
        where TEntityKey: IEntityKey
    {
        void Apply(ViewDelegates.Apply<TEntityKey, T1, T2, T3, T4, T5> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TEntityKey, TContext, T1, T2, T3, T4, T5> bulk);

    }

    public interface IPersistentEntityView<TEntityKey, T1, T2, T3, T4, T5>  : IEntityView<TEntityKey, T1, T2, T3, T4, T5>
        where TEntityKey: IEntityKey
    {
        int Count { get; }
    }

    public interface IEntityView<TEntityKey, T1, T2, T3, T4, T5, T6>  : IEntityView<TEntityKey>
        where TEntityKey: IEntityKey
    {
        void Apply(ViewDelegates.Apply<TEntityKey, T1, T2, T3, T4, T5, T6> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TEntityKey, TContext, T1, T2, T3, T4, T5, T6> bulk);

    }

    public interface IPersistentEntityView<TEntityKey, T1, T2, T3, T4, T5, T6>  : IEntityView<TEntityKey, T1, T2, T3, T4, T5, T6>
        where TEntityKey: IEntityKey
    {
        int Count { get; }
    }

    public interface IEntityView<TEntityKey, T1, T2, T3, T4, T5, T6, T7>  : IEntityView<TEntityKey>
        where TEntityKey: IEntityKey
    {
        void Apply(ViewDelegates.Apply<TEntityKey, T1, T2, T3, T4, T5, T6, T7> bulk);
        void ApplyWithContext<TContext>(TContext t, ViewDelegates.ApplyWithContext<TEntityKey, TContext, T1, T2, T3, T4, T5, T6, T7> bulk);

    }

    public interface IPersistentEntityView<TEntityKey, T1, T2, T3, T4, T5, T6, T7>  : IEntityView<TEntityKey, T1, T2, T3, T4, T5, T6, T7>
        where TEntityKey: IEntityKey
    {
        int Count { get; }
    }

  

}
