
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace EnttSharp.Entities
{
    public static partial class ViewDelegates 
    {
        public delegate void Apply<TEntityKey, T1>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4, T5>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6 )
            where TEntityKey: IEntityKey;
        public delegate void Apply<TEntityKey, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TEntityKey k,
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6, in T7 c7 )
            where TEntityKey: IEntityKey;

        public delegate void ApplyWithContext<TEntityKey, in TContext, T1, T2, T3, T4, T5, T6, T7>(IEntityViewControl<TEntityKey> v, TContext context, TEntityKey k, 
                        in T1 c1, in T2 c2, in T3 c3, in T4 c4, in T5 c5, in T6 c6, in T7 c7 )
            where TEntityKey: IEntityKey;

    }
}